spring.application.name=SmartPark-Campus

# Google OAuth 2.0 Configuration
google.oauth.client-id=645115511045-86514437mn48ffcsq67s7t9v32doqfrj.apps.googleusercontent.com
google.oauth.client-secret=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
google.oauth.redirect-uri=http://localhost:8080/auth/oauth/callback

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurposesOnlyPleaseDontShareThis
jwt.expiration=86400000

# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/smartpark_campus
spring.datasource.username=root
spring.datasource.password=9228
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server Configuration
server.port=8080
server.servlet.context-path=/

# JPA Configuration
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true