spring.application.name=SmartPark-Campus

# Google OAuth 2.0 Configuration
google.oauth.client-id=645115511045-86514437mn48ffcsq67s7t9v32doqfrj.apps.googleusercontent.com
google.oauth.client-secret=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
google.oauth.redirect-uri=http://localhost:8080/auth/oauth/callback

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurposesOnlyPleaseDontShareThis
jwt.expiration=86400000

# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://ep-wild-term-ancb1fap-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HhXxFE8kwo2A
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Configuration
server.port=8080
server.servlet.context-path=/

# JPA Configuration
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Multipart upload limits (ticket evidence images)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB